# Welcome to your prefect.yaml file! You can use this file for storing and managing
# configuration for deploying your flows. We recommend committing this file to source
# control along with your flow code.

# Generic metadata about this project
name: CTOS CCDC DATAOPS
prefect-version: null

# build section allows you to manage and build docker images
build: null

# push section allows you to manage if and how this project is uploaded to remote locations
push: null

# pull section allows you to provide instructions for cloning this project in remote locations
pull:
  - prefect.deployments.steps.git_clone:
      id: clone-step
      repository: https://github.com/CBIIT/CCDC-ETL.git
      branch: main
      include_submodules: True
  - prefect.deployments.steps.run_shell_script:
      script: npm ci
      directory: "{{ clone-step.directory }}"
      stream_output: True

deployments:
  - name: ccdc_deploy_etl_lower
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint: ccdc_deploy_etl_prefect.py:ccdc_deploy_etl_lower
    parameters:
      environment: dev
      etl_branch: main
      s3_folder: ""
      operation:
        - node dropTable.js
        - node createTable.js
        - node index.js
    work_pool:
      name: ccdi-dcc-32gb-prefect-3.4.19-python3.13
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "CCDC ETL"
          CCDC_ETL_TIER: lower
          CCDC_ETL_S3_BUCKET_ENV_VAR: CCDC_ETL_LOWER_TIER_S3_BUCKET
  
  - name: ccdc_deploy_etl_upper
    version: null
    tags: []
    description: null
    schedule: {}
    flow_name: null
    entrypoint: ccdc_deploy_etl_prefect.py:ccdc_deploy_etl_upper
    parameters:
      environment: stage
      etl_branch: main
      s3_folder: ""
      operation:
        - node dropTable.js
        - node createTable.js
        - node index.js
    work_pool:
      name: ccdi-dcc-prod-32gb-prefect-3.4.19-python3.13
      work_queue_name: default
      job_variables:
        env:
          PREFECT_LOGGING_EXTRA_LOGGERS: "CCDC ETL"
          CCDC_ETL_TIER: upper
          CCDC_ETL_S3_BUCKET_ENV_VAR: CCDC_ETL_UPPER_TIER_S3_BUCKET
